"""Constants and configuration values for EQ-Author."""

from typing import Dict

STEP_FILENAMES: Dict[int, str] = {
    1: "01_brainstorm_and_reflection.md",
    2: "02_characters.md",
    3: "03_intention_and_chapter_planning.md",
    4: "04_human_vs_llm_critique.md",
    5: "05_final_plan.md",
}

CHAPTER_WORD_TARGET = 2000
CHAPTER_MIN_WORDS = CHAPTER_WORD_TARGET
CHAPTER_MAX_ATTEMPTS = 5

WORD_RE_PATTERN = r"\b[\w'\-]+\b"

DEFAULT_CONTEXT_STRATEGY = "aggressive"
DEFAULT_SUMMARY_LENGTH = 250
DEFAULT_RECENT_CHAPTERS = 2
CONTEXT_WARNING_THRESHOLD = 0.75
CONTEXT_CRITICAL_THRESHOLD = 0.90

DEFAULT_MAX_CONTEXT_TOKENS = 8000
DEEPSEEK_REASONER_MAX_TOKENS = 128000
DEEPSEEK_REASONER_DEFAULT_TOKENS = 32000

DEFAULT_MAX_OUTPUT_TOKENS = 4000
DEEPSEEK_MAX_OUTPUT_TOKENS = 8192
DEEPSEEK_REASONER_MAX_OUTPUT_TOKENS = 16384

DEFAULT_TEMPERATURE = 1.0
DEEPSEEK_REASONER_TEMPERATURE = 1.0
